[package]
name = "apkeep"
version = "0.8.0"
authors = ["William Budington <bill@eff.org>"]
edition = "2018"
license = "MIT"
description = "A command-line tool for downloading APK files from various sources"
homepage = "https://github.com/EFForg/apkeep"
repository = "https://github.com/EFForg/apkeep"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["stream"] }
futures-util = { version = "0.3", features = ["io"] }
regex = "1.5"
clap = "2.3"
gpapi = "0.5"
tokio-dl-stream-to-disk = { version = "0.3", features = ["sha256sum"] }
tempfile = "3"
dirs = "4.0"
zip = "0.5"
cryptographic-message-syntax = "0.5"
openssl = "0.10"
x509-certificate = "0.5"
simple-error = "0.2"
sha-1 = "0.9"
base64 = "0.13"
serde_json = "1"
hex = "0.4"

[build-dependencies]
clap = "2.3"
